### Get Users
GET http://localhost:3000/users HTTP/1.1
### Get User
GET http://localhost:3000/users/2bb65ab3-cc42-40a8-b693-451781532851 HTTP/1.1
### Create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jorge",
    "email": "jorge@gmail.com"
}

### Update user
PATCH http://localhost:3000/users/2bb65ab3-cc42-40a8-b693-451781532851 HTTP/1.1
Content-Type: application/json

{
    "name": "Carlitos"
}